[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "MassVision"
authors = [{name = "Amoon Jamzad", email = "a.jamzad@queensu.ca"}]
dynamic = ["version", "description"]
